=== gnomix/T.A.L.K./connectors/java/JTAPIConnector/CTIServer/src/org/wybecom/talk/jtapi/stateserver/client/config/stateserverclientconfig.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://xml.netbeans.org/schema/stateserverclientconfig"
            xmlns:tns="http://xml.netbeans.org/schema/stateserverclientconfig"
            elementFormDefault="qualified">
    <xsd:complexType name="xmlstateserverclient">
        <xsd:sequence>
            <xsd:element name="wsdlurl" type="xsd:string"></xsd:element>
            <xsd:element name="event" type="tns:xmlevent" maxOccurs="unbounded" minOccurs="0"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="stateserverclientconfig">
        <xsd:sequence>
            <xsd:element name="stateserverclient" type="tns:xmlstateserverclient" maxOccurs="unbounded" minOccurs="0"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="configuration" type="tns:stateserverclientconfig"></xsd:element>
    <xsd:complexType name="xmlevent">
        <xsd:attribute name="name" type="xsd:string"/>
        <xsd:attribute name="enabled" type="xsd:boolean"/>
    </xsd:complexType>
</xsd:schema>

=== gnomix/T.A.L.K./connectors/java/JTAPIConnector/CTIServer/src/org/wybecom/talk/jtapi/stateserver/client/config/stateserverclientconfig.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : stateserverclientconfig2.xml
    Created on : 25 juin 2009, 19:17
    Author     : barreyo
    Description:
        Purpose of the document follows.
-->

<ns0:configuration  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns0='http://xml.netbeans.org/schema/stateserverclientconfig'
   xsi:schemaLocation='http://xml.netbeans.org/schema/stateserverclientconfig stateserverclientconfig.xsd'>
        <ns0:stateserverclient>
                <ns0:wsdlurl></ns0:wsdlurl>
                <ns0:event name="" enabled=""></ns0:event>
                <ns0:event name="" enabled=""></ns0:event>
                <ns0:event name="" enabled=""></ns0:event>
            </ns0:stateserverclient>
        <ns0:stateserverclient>
                <ns0:wsdlurl></ns0:wsdlurl>
                <ns0:event name="" enabled=""></ns0:event>
                <ns0:event name="" enabled=""></ns0:event>
                <ns0:event name="" enabled=""></ns0:event>
            </ns0:stateserverclient>
        <ns0:stateserverclient>
                <ns0:wsdlurl></ns0:wsdlurl>
                <ns0:event name="" enabled=""></ns0:event>
                <ns0:event name="" enabled=""></ns0:event>
                <ns0:event name="" enabled=""></ns0:event>
            </ns0:stateserverclient>

</ns0:configuration>
