=== gnomix/T.A.L.K./connectors/java/JTAPIConnector/CTIServer/src/org/wybecom/talk/jtapi/configuration/cticonfig.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://xml.netbeans.org/schema/cticonfig"
            xmlns:tns="http://xml.netbeans.org/schema/cticonfig"
            elementFormDefault="qualified">
    <xsd:complexType name="xmlprovider">
        <xsd:sequence>
            <xsd:element name="ctiprovider" type="xsd:string"></xsd:element>
            <xsd:element name="ctiuser" type="xsd:string"></xsd:element>
            <xsd:element name="ctiuserpassword" type="xsd:string"></xsd:element>
            <xsd:element name="backupctiprovider" type="xsd:string"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="cticonfig">
        <xsd:sequence>
            <xsd:element name="provider" type="tns:xmlprovider" maxOccurs="unbounded" minOccurs="0"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="configuration" type="tns:cticonfig"></xsd:element>
</xsd:schema>

=== gnomix/T.A.L.K./connectors/java/JTAPIConnector/CTIServer/src/org/wybecom/talk/jtapi/configuration/cticonfig.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : cticonfig.xml
    Created on : 25 juin 2009, 16:01
    Author     : barreyo
    Description:
        Purpose of the document follows.
-->

<ns0:configuration  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns0='http://xml.netbeans.org/schema/cticonfig'
   xsi:schemaLocation='http://xml.netbeans.org/schema/cticonfig cticonfig.xsd'>
        <ns0:provider>
                <ns0:ctiprovider></ns0:ctiprovider>
                <ns0:ctiuser></ns0:ctiuser>
                <ns0:ctiuserpassword></ns0:ctiuserpassword>
                <ns0:backupctiprovider></ns0:backupctiprovider>
            </ns0:provider>
        <ns0:provider>
                <ns0:ctiprovider></ns0:ctiprovider>
                <ns0:ctiuser></ns0:ctiuser>
                <ns0:ctiuserpassword></ns0:ctiuserpassword>
                <ns0:backupctiprovider></ns0:backupctiprovider>
            </ns0:provider>
        <ns0:provider>
                <ns0:ctiprovider></ns0:ctiprovider>
                <ns0:ctiuser></ns0:ctiuser>
                <ns0:ctiuserpassword></ns0:ctiuserpassword>
                <ns0:backupctiprovider></ns0:backupctiprovider>
            </ns0:provider>

</ns0:configuration>
